LastROMFolder = "C:/NintendoDS/Jogos/nds"
UITheme = ""
RecentROM = [
    "roms/nds/MarioKart.nds",
    "C:/NintendoDS/Jogos/nds/Mario Kart DS (USA, Australia) (En,Fr,De,Es,It).nds",
]
FastForwardFPS = 1000.0
PauseLostFocus = false
AudioSync = false
TargetFPS = 60.0
LimitFPS = true
SlowmoFPS = 30.0

[Mic]
InputType = 1
Device = ""
WavPath = ""

[Instance0]
EnableCheats = false
SaveFilePath = ""
JoystickID = 0
SavestatePath = ""
CheatFilePath = ""

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM7]
Port = 3334
BreakOnStartup = false

[Instance0.Gdb.ARM9]
Port = 3333
BreakOnStartup = false

[Instance0.Window1]
Enabled = false

[Instance0.Firmware]
Username = "melonDS"
Language = 1
FavouriteColour = 0
BirthdayMonth = 1
BirthdayDay = 1
Message = ""
MAC = ""

[Instance0.Joystick]
HK_FastForwardToggle = -1
HK_VolumeUp = -1
HK_SolarSensorDecrease = -1
HK_VolumeDown = -1
HK_SolarSensorIncrease = -1
R = -1
L = -1
HK_GuitarGripRed = -1
A = -1
Y = -1
HK_FrameStep = -1
HK_Lid = -1
HK_SlowMoToggle = -1
HK_GuitarGripYellow = -1
HK_FrameLimitToggle = -1
Up = -1
HK_GuitarGripGreen = -1
HK_GuitarGripBlue = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
X = -1
B = -1
Down = -1
HK_Mic = -1
HK_FastForward = -1
Left = -1
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_PowerButton = -1
HK_Reset = -1

[Instance0.Keyboard]
HK_FastForwardToggle = -1
HK_VolumeUp = -1
HK_SolarSensorDecrease = -1
HK_VolumeDown = -1
HK_SolarSensorIncrease = -1
R = -1
L = -1
HK_GuitarGripRed = -1
A = -1
Y = -1
HK_FrameStep = -1
HK_Lid = -1
HK_SlowMoToggle = -1
HK_GuitarGripYellow = -1
HK_FrameLimitToggle = -1
Up = -1
HK_GuitarGripGreen = -1
HK_GuitarGripBlue = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
X = -1
B = -1
Down = -1
HK_Mic = -1
HK_FastForward = -1
Left = -1
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_PowerButton = -1
HK_Reset = -1

[Instance0.Window2]
Enabled = false

[Instance0.RTC]
Offset = 0

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.Window0]
ShowOSD = true
Geometry = "AdnQywADAAAAAAHAAAAAugAABNQAAAMFAAABwAAAANgAAATUAAADBQAAAAAAAAAABgAAAAHAAAAA2AAABNQAAAMF"
ScreenLayout = 0
ScreenRotation = 0
ScreenAspectBot = 0
ScreenGap = 0
ScreenSwap = false
ScreenSizing = 0
IntegerScaling = false
ScreenAspectTop = 0
ScreenFilter = false
Enabled = true

[Instance0.Window3]
Enabled = false

[Instance0.Audio]
Volume = 256
DSiVolumeSync = false

[LAN]
DirectMode = false

[MP]
RecvTimeout = 25
AudioMode = 1

[3D]
Renderer = 0

[3D.Soft]
Threaded = true

[Savestate]
RelocSRAM = false

[Emu]
ConsoleType = 0
ExternalBIOSEnable = false
DirectBoot = true

[Screen]
UseGL = false

[JIT]
MaxBlockSize = 32
LiteralOptimisations = true
BranchOptimisations = true
FastMemory = true
Enable = false

[Audio]
BitDepth = 0
Interpolation = 0

[Mouse]
HideSeconds = 5
Hide = false

[DLDI]
Enable = false

[DSi]
NANDPath = ""

[DSi.Camera0]
XFlip = false
InputType = 0
ImagePath = ""
DeviceName = ""

[DSi.Camera1]
XFlip = false
InputType = 0
ImagePath = ""
DeviceName = ""

